spring:
  application:
    name: mvc-service

server:
  port: 9001
  servlet:
    context-path: /mvc-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10