spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: mvc-service
              uri: lb://mvc-service
              predicates:
                - Path=/mvc-service/**
            - id: flux-service
              uri: lb://flux-service
              predicates:
                - Path=/flux-service/**

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10