server:
  port: 9000

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: mvc-service
              uri: lb://mvc-service
              predicates:
                - Path=/mvc-service/**
            - id: flux-service
              uri: lb://flux-service
              predicates:
                - Path=/flux-service/*
