spring:
  kafka:
    bootstrap-servers: localhost:7007
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${kafka.stream.consumer.group-id}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  graphql:
    cors:
      allowed-origins:
        - "http://localhost:3000"
      allowed-methods: GET,POST,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
    graphiql:
      enabled: true
    websocket:
      path: "/graphql"

server:
  port: 7000

kafka:
  topic:
    message:
      name: message-topic
    stock-price:
      name: stock-price-topic
  consumer:
    message:
      group-id: message-consumer-group
      reactive-group-id: message-reactive-consumer-group
    stock-price:
      reactive-group-id: stock-price-reactive-consumer-group
